logging:
  level:
    com.throttlex: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: throttlex
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/throttlex?options=-c%20statement_timeout=10000
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 5000     # 5 seconds
      idle-timeout: 300000         # 5 minutes (Must be less than max-lifetime)
      max-lifetime: 600000         # 10 minutes
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          query:
            timeout: 10000         # 10 seconds JPA query timeout
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        spring.json.add.type.headers: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      ssl:
        enabled: false
      timeout: 200ms
      connect-timeout: 300ms
      lettuce:
        pool:
          enabled: true
          max-active: 64
          max-idle: 32
          min-idle: 8
          max-wait: 1000ms
          time-between-eviction-runs: 30s

resilience4j:
  circuitbreaker:
    instances:
      redisRateLimiter:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        minimum-number-of-calls: 20
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 200ms
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true

  bulkhead:
    instances:
      redisRateLimiter:
        max-concurrent-calls: 100
        max-wait-duration: 20ms

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    redis:
      enabled: true

throttlex:
  rate-limit:
    fallback:
      mode: FAIL_CLOSED
      local:
        max-requests-per-window: 20
        window-seconds: 60
